<?php 
    $user = new Zend\Session\Container('user');
?>
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/"><?php echo $this->translate('DASHBOARD_TITLE'); ?></a>
    </div>
    <!-- /.navbar-header -->

    <ul class="nav navbar-top-links navbar-right">
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li><a href="#"><i class="fa fa-user fa-fw"></i> <?php echo (isset($user->name) ? $user->name : ''); ?></a>
                </li>
                <li class="divider"></li>
                <li><a href="<?php echo $this->url('login', array('action' => 'logout')) ?>"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                </li>
            </ul>
            <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
    </ul>
    <!-- /.navbar-top-links -->

    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
                <li>
                    <a href="/"><i class="fa fa-dashboard fa-fw"></i> Home </a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Statistic <span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="/dashboard/userstatistic"> <i class="fa fa-user fa-fw"></i>User Statistic </a>
                        </li>
                        <li>
                            <a href="/dashboard/bandwidthstatistic"><i class="fa fa-chain fa-fw"></i>Bandwidth Statistic</a>
                        </li>
                        <li>
                            <a href="/dashboard/paymentstatistic"><i class="fa fa-paypal fa-fw"></i>Payment</a>
                        </li>
                    </ul>
                    <!-- /.nav-second-level -->
                </li>
                <li>
                    <a href="/users"><i class="fa fa-user fa-fw"></i> User Managerment</a>
                </li>
                <li>
                    <a href="/modules"><i class="fa fa-deviantart fa-fw"></i> Module Managerment</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-envelope fa-fw"></i> Packet Managerment <span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="/modules/category"> <i class="fa fa-user fa-fw"></i>Category</a>
                        </li>
                        <li>
                            <a href="/modules/packet"><i class="fa fa-chain fa-fw"></i>Packets</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="/payments"><i class="fa fa-money fa-fw"></i> Payment Managerment</a>
                </li>



            </ul>
        </div>
        <!-- /.sidebar-collapse -->
    </div>
    <!-- /.navbar-static-side -->
</nav>
