<nav class="navbar " role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <?php echo "<pre>";
 print_r($this);
 echo "</pre>";
 exit();?>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>