
<h1><?php echo $this->translate('Transaction'); ?></h1>

<table class='table table-hover'>
    <tbody>
        <tr>
            <td class="col-md-2"><?php echo $this->translate('Token'); ?></td>
            <td class="col-md-10"><?php echo $this->escapehtml($transaction->__call('getToken', 'token')); ?></td>
        </tr>

        <tr>
            <td><?php echo $this->translate('ACK'); ?></td>
            <td><?php echo $this->escapehtml($transaction->__call('getACK', 'ack')); ?></td>
        </tr>

        <?php if(count($transaction->getErrors()) > 0) { ?>
            <tr>
                <td><?php echo $this->translate("Errors"); ?></td>
                <td>
                    <ul class="list-unstyled">
                        <?php foreach($transaction->getErrors() as $error) { ?>
                            <li><?php echo $this->escapeHtml(sprintf('%s (%s)', $error['LONGMESSAGE'], $error['SHORTMESSAGE'])); ?></li>
                        <?php } ?>
                    </ul>
                </td>
            </tr>
        <?php } ?>

        <tr>
            <td><?php echo $this->translate('Time'); ?></td>
            <td><?php echo $this->escapehtml($transaction->__call('getTimestamp', 'timestamp')); ?></td>
        </tr>

        <tr>
            <td><?php echo $this->translate('Transaction'); ?></td>
            <td><a href='<?php echo $this->url('payments-read', ['id' => $transaction->__call('getPaymentInfo', 'PaymentInfo')[0]['TRANSACTIONID']]); ?>'><?php echo $this->escapehtml($transaction->__call('getPaymentInfo', 'PaymentInfo')[0]['TRANSACTIONID']); ?></a></td>
        </tr>

        <tr>
            <td><?php echo $this->translate('Status'); ?></td>
            <td><?php echo $this->escapehtml($transaction->__call('getPaymentInfo', 'PaymentInfo')[0]['PAYMENTSTATUS']); ?></td>
        </tr>

        <tr>
            <td><?php echo $this->translate('AMT'); ?></td>
            <td><?php echo $this->escapehtml($transaction->__call('getPaymentInfo', 'PaymentInfo')[0]['AMT']); ?></td>
        </tr>

        <tr>
            <td><?php echo $this->translate('ACK'); ?></td>
            <td><?php echo $this->escapehtml($transaction->__call('getPaymentInfo', 'PaymentInfo')[0]['ACK']); ?></td>
        </tr>
    </tbody>
</table>