
<h1><?php echo $this->escapeHtml('Transactions'); ?></h1>

<?php  ?>
    <table class='table table-hover'>
            <tr>
                <th>ID</th>
                <th>Username</th>
                <th>Days</th>
                <th>Total</th>
                <th>Action</th>
            </tr>
            <tr>
                <td>ID</td>
                <td>Username</td>
                <td>Days</td>
                <td>Total</td>
                <td>Action</td>
            </tr>
    </table>