
<h1><?php echo $this->escapeHtml('Transactions'); ?></h1>

<?php if(count($transactions) > 0) { ?>
    <table class='table table-hover'>
        <thead>
            <tr>
                <th><?php echo $this->escapeHtml('Transaction'); ?></th>
                <th><?php echo $this->escapeHtml('Name'); ?></th>
                <th><?php echo $this->escapeHtml('Email'); ?></th>
                <th><?php echo $this->escapeHtml('Type'); ?></th>
                <th><?php echo $this->escapeHtml('Status'); ?></th>
                <th><?php echo $this->escapeHtml('AMT'); ?></th>
                <th><?php echo $this->escapeHtml('Currency'); ?></th>
            </tr>
        </thead>

        <tbody>
            <?php foreach($transactions as $transaction) { ?>
                <tr>
                    <td><a href='<?php echo $this->url('payments-read', ['id' => $transaction['TRANSACTIONID']]); ?>'><?php echo $this->escapehtml($transaction['TRANSACTIONID']); ?></a></td>
                    <td><?php echo $this->escapehtml($transaction['NAME']); ?></td>
                    <td><?php echo isset($transaction['EMAIL']) ? $this->escapehtml($transaction['EMAIL']) : 'n/a'; ?></td>
                    <td><?php echo $this->escapehtml($transaction['TYPE']); ?></td>
                    <td><?php echo $this->escapehtml($transaction['STATUS']); ?></td>
                    <td><?php echo $this->escapehtml($transaction['AMT']); ?></td>
                    <td><?php echo $this->escapehtml($transaction['CURRENCYCODE']); ?></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
<?php } else { ?>
    <div class="alert alert-danger"><?php echo $this->translate("There are no transactions"); ?></div>
<?php } ?>

<hr />

<a class='btn btn-success' href="<?php echo $this->url('payments-create'); ?>">
    <?php echo $this->translate("Create"); ?>
</a>