<div class="container-fluid text-center">
    <div class="row">
      <div class="col-md-1 table-bordered" style="padding:10px 0">ID</div>
      <div class="col-md-3 table-bordered" style="padding:10px 0">Tên Người Dùng</div>
      <div class="col-md-3 table-bordered" style="padding:10px 0">Thời Gian Bắt Đầu</div>
      <div class="col-md-3 table-bordered" style="padding:10px 0">Băng Thông</div>
      
    </div>
    <div class="row">
      <div class="col-md-1 table-bordered">1</div>
      <div class="col-md-3 table-bordered">Hoang</div>
      <div class="col-md-3 table-bordered">18:35pm 15/5/2015</div>
      <div class="col-md-3 table-bordered">100MB</div>
      </div>
    </div>
</div>