<div class="container-fluid text-center">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>
                    <?php echo $this->translate('ID_TITLE'); ?>
                </th>
                <th>
                    <?php echo $this->translate('NAME_TITLE'); ?>
                </th>
                <th>
                    <?php echo $this->translate('START_TIME_TITLE'); ?>
                </th>
                <th>
                    <?php echo $this->translate('BANDWIDTH'); ?>
                </th>
            </tr>

        </thead>
        <tbody>
            <?php
            $i = 0;
            foreach ($users as $user) :
                ?>
                <tr>
                    <td>
                        <?php echo $i++; ?> 
                    </td>
                    <td>
                        <?php echo $user['user']['username']; ?> 
                    </td>
                    <td>
                        <?php echo $user['user']['acctstarttime']; ?> 
                    </td>
                    <td>
                        <?php
                        $bw = $user['bandwidth'];
                        $unit = array('B', 'Kb', 'Mb', 'Gb', 'Tb');
                        $i = 0;
                        while ($bw - 100 >= 0):
                            $i++;
                            $bw /= 1024;
                        endwhile;
                        echo round($bw, 2) . ' ' . $unit[$i];
                        ?> 
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>    
    </table>

</div>
</div>