<div class="row">
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-user fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge"><?php echo (isset($sums['userlogged'])) ? $sums['userlogged'] : '0'; ?></div>
                        <div><?php echo $this->translate('USER_LOGINED'); ?></div>
                    </div>
                </div>
            </div>
            <a href="<?php echo $this->url('dashboard', array('action' => 'userstatistic')); ?>">
                <div class="panel-footer">
                    <span class="pull-left"><?php echo $this->translate('DETAIL_VIEW'); ?></span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-user fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge"><?php
                            $unit = array('B','Kb','Mb','Gb','Tb');
                            $i = 0;
                            $bw = (isset($sums['bandwidthtrafic'])) ? $sums['bandwidthtrafic'] : '0';
                            while($bw - 100 >= 0):
                                $i++;
                                $bw /= 1024;
                            endwhile;
                            echo round($bw,2).' '.$unit[$i];
                            ?></div>
                        <div><?php echo $this->translate('BANDWIDTH_TRAFIC'); ?></div>
                    </div>
                </div>
            </div>
            <a href="<?php echo $this->url('dashboard', array('action' => 'bandwidthstatistic')); ?>">
                <div class="panel-footer">
                    <span class="pull-left"><?php echo $this->translate('DETAIL_VIEW'); ?></span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-user fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge"><?php echo (isset($sums['payment'])) ? $sums['payment'] : '0'; ?></div>
                        <div><?php echo $this->translate('PAYMENT'); ?></div>
                    </div>
                </div>
            </div>
            <a href="<?php echo $this->url('dashboard', array('action' => 'paymentstatistic')); ?>">
                <div class="panel-footer">
                    <span class="pull-left"><?php echo $this->translate('DETAIL_VIEW'); ?></span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-user fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge"><?php echo (isset($sums['freeuserlogged'])) ? $sums['freeuserlogged'] : '0'; ?></div>
                        <div><?php echo $this->translate('FREE_USER_LOGINED'); ?></div>
                    </div>
                </div>
            </div>
            <a href="<?php echo $this->url('dashboard', array('action' => 'userstatistic')); ?>">
                <div class="panel-footer">
                    <span class="pull-left"><?php echo $this->translate('DETAIL_VIEW'); ?></span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
</div>
