<h1><?php echo $this->escapeHtml('Transactions'); ?></h1>

<?php if(count($transactions) > 0) { ?>
    <table class='table table-hover'>
        <thead>
            <tr>
                <th>STT</th>
                <th>Username</th>
                <th>Order Date</th>
                <th>Status</th>
                <th>Total</th>
            </tr>
        </thead>

        <tbody>
            <?php foreach($transactions as $transaction) { ?>
                <tr>
                    <td><?php echo $this->escapehtml($transaction->getOrderid()); ?></td>
                    <td><?php $u = $user->getUser($transaction->getOrderid()); echo $this->escapehtml($u->getUsername()); ?></td>
                    <td><?php echo $this->escapehtml($transaction->getOrderdate()); ?></td>
                    <td><?php echo $this->escapehtml($transaction->getStatus()); ?></td>
                    <td><?php echo $this->escapehtml(number_format($transaction->getSumtotal())).' VND'; ?></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
<?php } else { ?>
    <div class="alert alert-danger"><?php echo $this->translate("There are no transactions"); ?></div>
<?php } ?>