<div class="row">
    <div class="col-lg-12">
        <table class="table table-bordered">
            <thead>
                <tr class="text-info center bg-info">
                    <th>
                        <?php echo $this->translate('ID_TITLE') ?>
                    </th>
                    <th>
                        <?php echo $this->translate('USERNAME_TITLE') ?>
                    </th>
                    <th>
                        <?php echo $this->translate('START_TIME_TITLE') ?>
                    </th>
                    <th>
                        <?php echo $this->translate('STATUS_TITLE') ?>
                    </th>
                    <th>
                        <?php echo $this->translate('ACTION_TITLE') ?>
                    </th>
                </tr>
            </thead>
            <tbody>
               <?php foreach ($users as $user) : ?>
                <tr class="center">
                        <td>
                            <?php echo $this->escapeHtml($user['user']['radacctid']); ?>
                        </td>
                        <td>
                            <?php echo $this->escapeHtml($user['user']['username']); ?>
                        </td>
                        <td>
                            <?php echo $this->escapeHtml($user['user']['acctstarttime']); ?>
                        </td>
                        <td>
                            <?php echo ($user['status']) ? 'Online' : 'Offline' ?>
                        </td>
                        <td>
                            <a class="btn btn-primary deconnect <?php echo ($user['status']) ? '' : 'disabled'; ?>"  value="<?php echo $this->escapeHtml($user['user']['radacctid']); ?>" data-mac="<?php echo $user['user']['callingstationid']; ?>"><?php echo $this->translate('DISCONNECT_BTN'); ?></a>
                        </td>
                    </tr>
                <?php endforeach; ?> 
            </tbody>
        </table>
        <?php
        // add at the end of the file after the table
        echo $this->paginationControl(
                // the paginator object
                $this->paginator,
                // the scrolling style
                'sliding',
                // the partial to use to render the control
                'partials/shared/paging.phtml',
                // the route to link to when a user clicks a control link
                array(
            'route' => 'users',
            'options' => array('acton' => 'userstatistic')
                )
        );
        ?>
    </div>

</div>

