<?php echo $this->navigation('navigation')->menu()->setPartial('partials/usermenu.phtml'); ?>
<div class="container">
    <div class="row">
        <div role="tabpanel">
            <!-- Nav tabs -->
            <ul class="nav nav-tabs" role="tablist">
                <li role="presentation" class="active"><a href="#general" aria-controls="general" role="tab" data-toggle="tab"><?php echo $this->translate('USER_GENERAL');?></a></li>
                <li role="presentation"><a href="#information" aria-controls="information" role="tab" data-toggle="tab"><?php echo $this->translate('USER_PROFILE');?></a></li>
                <li role="presentation"><a href="#package" aria-controls="package" role="tab" data-toggle="tab"><?php echo $this->translate('USER_PACKET');?></a></li>
                <li role="presentation"><a href="#orders" aria-controls="orders" role="tab" data-toggle="tab"><?php echo $this->translate('USER_ORDER');?></a></li>
            </ul>

            <!-- Tab panes -->
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane active" id="general">1...</div>
                <div role="tabpanel" class="tab-pane" id="information">2...</div>
                <div role="tabpanel" class="tab-pane" id="package">3...</div>
                <div role="tabpanel" class="tab-pane" id="orders">4...</div>
            </div>

        </div>
    </div>
</div>