<?php if (isset($message)): ?>
    <div class="col-md-12 col-sm-12 col-xs-12 alert alert-danger">
        <?php echo (isset($message)) ? $message : ""; ?>
    </div>
<?php endif; ?> <?php
$form->setAttribute('action', $this->url('register', array('action' => 'index')));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
?>
<div class="container">
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title alert alert-success" style="text-align: center; color: #202020; text-transform: uppercase; font-size: 20px"><?php echo $this->translate('_WELLCOME');?></h3>
                    <p style="text-align: center; font-size: 16px; margin-top: 10px"><?php echo $this->translate('MESSAGE_WELLCOME');?></p>
                </div>
                <div class="panel-body">
                    <?php echo $this->form()->openTag($form); ?>
                    <div class="form-group">
                        <label for="username" class="col-md-2 control-label"><?php echo $this->translate('USERNAME_TITLE'); ?></label>
                        <div class="col-md-10">
                            <?php echo $this->formRow($form->get('username')); ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="fullname" class="col-md-2 control-label"><?php echo $this->translate('FULLNAME_TITLE'); ?></label>
                        <div class="col-md-10">
                            <?php echo $this->formRow($form->get('fullname')); ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="password" class="col-md-2 control-label"><?php echo $this->translate('PASSWORD_TITLE'); ?></label>
                        <div class="col-md-10">
                            <?php echo $this->formRow($form->get('password')); ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="re-password" class="col-md-2 control-label"><?php echo $this->translate('RETYPEPASSWORD_TITLE'); ?></label>
                        <div class="col-md-10">
                            <?php echo $this->formRow($form->get('retype')); ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="email" class="col-md-2 control-label"><?php echo $this->translate('EMAIL_TITLE'); ?></label>
                        <div class="col-md-10">
                            <?php echo $this->formRow($form->get('email')); ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="phonenumber" class="col-md-2 control-label"><?php echo $this->translate('PHONE_TITLE'); ?></label>
                        <div class="col-md-10">
                            <?php echo $this->formRow($form->get('phone')); ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="building" class="col-md-2 control-label"><?php echo $this->translate('BUILDING_TITLE'); ?></label>
                        <div class="col-md-10">
                            <?php echo $this->formRow($form->get('building')); ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="room" class="col-md-2 control-label"><?php echo $this->translate('ROOM_TITLE'); ?></label>
                        <div class="col-md-10">
                            <?php echo $this->formRow($form->get('room')); ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="room" class="col-md-2 control-label"><?php echo $this->translate('ROOM_TITLE'); ?></label>
                        <div class="col-md-10">
                            <?php echo $this->formRow($form->get('packet')); ?>
                        </div>
                    </div>
                    <div class="form-actions nobg fluid">
                        <div class="col-md-offset-2">
                            <button class="btn btn-success" id='btn-ok' name='ok' type='submit'><?php echo $this->translate('REG_SUBMIT_TITLE'); ?></button>
                            <a class="btn btn-success" id='btn-ok' name='ok' href="/register/auto"><?php echo $this->translate('AUTO_SUBMIT_TITLE'); ?></a>
                        </div>
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>