<?php

$form->setAttribute('action', $this->url('register', array('action' => 'index')));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php foreach ($form as $key => $value): ?>
    <div class="row">
<!--        <div class="col-sm-2 col-md-3 col-xs-1"></div>
        <div class="col-sm-8 col-md-6 col-xs-10">-->
            <?php echo $this->formRow($value); ?>
<!--        </div>
        <div class="col-sm-2 col-md-3 col-xs-1"></div>-->
    </div>
<?php endforeach; ?>
<?php echo $this->form()->closeTag(); ?>