<div class="row">
    <form action="/register/verify" method="post">
    <div class="col-sm-6 col-md-6 col-xs-12">
        <div class="row">
            <div class="col-sm-12 col-md-12 col-xs-12">
                <?php echo $code;?>
            </div>
            <div class="col-sm-12 col-md-12 col-xs-12">
                <input name="verify" type="text">
                <input name="username" type="text" value="<?php echo (isset($username)?$username:'');?>" <?php echo (!isset($username))?'placeholder="Please input username"':'hidden'?>>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-md-6 col-xs-12">
        <input type="submit" name="submit">
    </div>
    </form>
</div>