<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

       <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
                ->prependStylesheet($this->basePath('css/morris.css'))
                ->prependStylesheet($this->basePath('css/sb-admin-2.css'))
                ->prependStylesheet($this->basePath('css/timeline.css'))
                ->prependStylesheet($this->basePath('css/metisMenu.min.css'))
                ->prependStylesheet($this->basePath('css/custom.css'))
                ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath('js/custom.js'))
                ->prependFile($this->basePath('js/metisMenu.min.js'))
                ->prependFile($this->basePath('js/raphael-min.js'))
                
                ->prependFile($this->basePath('js/sb-admin-2.js'))
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery.min.js'))
                ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath('js/html5shiv.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>

    </head>
    <body>
        <div id="wrapper">
            <!-- Navigation -->
                               
            <?php echo $this->navigation('navigation')->menu()->setPartial('partials/menu.phtml'); ?>
            <!-- End navigation -->
            <!-- content trashable -->
            <div id="page-wrapper">
                <?php echo $this->content; ?>
            </div>
        </div><!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>