<div class="row">
    <form action="">
    <div class="col-sm-6 col-md-6 col-xs-12">
        <div class="row">
            <div class="col-sm-12 col-md-12 col-xs-12">
                <?php echo $code;?>
            </div>
            <div class="col-sm-12 col-md-12 col-xs-12">
                
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-md-6 col-xs-12">
        
    </div>
    </form>
</div>