
<form class="form-horizontal" action="addUser" method="post" id="form-add">
        	<div class="form-group">
                <label for="username" class="col-md-2 control-label">Username</label>
                <div class="col-md-4">
                    <input type="text" required="required" id='username' name='username' placeholder="Username ..." class='form-control'>
                </div>
            </div>
            <div class="form-group">
                <label for="fullname" class="col-md-2 control-label">Fullname</label>
                <div class="col-md-4">
                    <input type="text"  required="required" id='fullname' name='fullname' placeholder="Fullname ..." class='form-control'>
                </div>
            </div>
            <div class="form-group">
                <label for="password" class="col-md-2 control-label">Password</label>
                <div class="col-md-4">
                    <input type="password" id="password1" required="required" id='password' name='password' placeholder="Password ..." class='form-control'>
                </div>
            </div>
            <div class="form-group">
                <label for="re-password" class="col-md-2 control-label">Re-Password</label>
                <div class="col-md-4">
                    <input type="password" id="password2" required="required" id='re-password' name='re-password' placeholder="Re-Password ..." class='form-control'>
                </div>
            </div>
            <div class="form-group">
                <label for="email" class="col-md-2 control-label">Email</label>
                <div class="col-md-4">
                    <input type="email" required="required" id='email' name='email' placeholder="Email ..." class='form-control'>
                </div>
            </div>
            <div class="form-group">
                <label for="phonenumber" class="col-md-2 control-label">Phone Number</label>
                <div class="col-md-4">
                    <input type="text" required="required" id='phonenumber' name='phone' placeholder="Phone Number ..." class='form-control'>
                </div>
            </div>
            <div class="form-group">
                <label for="room" class="col-md-2 control-label">Room</label>
                <div class="col-md-4">
                    <input type="text" required="required" id='room' name='room' placeholder="Room ..." class='form-control'>
                </div>
            </div>
            <div class="form-group">
                <label for="packet" class="col-sm-2 control-label">Packet</label>
                <div class="col-sm-4">
                    <select class="form-control" name="packet">
                       <?php foreach ($packet as $item): ?>
                        <option value="<?php echo $item->getId(); ?>"><?php echo $item->getName(); ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label for="room" class="col-md-2 control-label">Building</label>
                <div class="col-md-4">
                    <input type="text"  required="required"id='room' name='building' placeholder=" ..." class='form-control'>
                </div>
            </div>
            <div class="form-actions nobg fluid">
                <div class="col-md-offset-2">
                    <button class="btn" id='btn-ok' name='ok' type='submit'>Tạo</button>
                </div>
            </div>
        </form>
<script>
    $('#form-add').submit(function(){
        if($('#password1').val()!=$('#password2').val())
        {
            alert('Password is not same');
            return false;
        }
    })
</script>