<div class="fix">
    	<form class="form-horizontal">
        	<div class="form-group">
                <label for="username" class="col-md-2 control-label">Username</label>
                <div class="col-md-4">
                    <input type="text" id='username' name='username' placeholder="Username ..." class='form-control'>
                </div>
            </div>
            <div class="form-group">
                <label for="fullname" class="col-md-2 control-label">Fullname</label>
                <div class="col-md-4">
                    <input type="text" id='fullname' name='fullname' placeholder="Fullname ..." class='form-control'>
                </div>
            </div>
            <div class="form-group">
                <label for="password" class="col-md-2 control-label">Password</label>
                <div class="col-md-4">
                    <input type="password" id='password' name='password' placeholder="Password ..." class='form-control'>
                </div>
            </div>
            <div class="form-group">
                <label for="re-password" class="col-md-2 control-label">Re-Password</label>
                <div class="col-md-4">
                    <input type="password" id='re-password' name='re-password' placeholder="Re-Password ..." class='form-control'>
                </div>
            </div>
            <div class="form-group">
                <label for="email" class="col-md-2 control-label">Email</label>
                <div class="col-md-4">
                    <input type="email" id='email' name='email' placeholder="Email ..." class='form-control'>
                </div>
            </div>
            <div class="form-group">
                <label for="phonenumber" class="col-md-2 control-label">Phone Number</label>
                <div class="col-md-4">
                    <input type="text" id='phonenumber' name='phonenumber' placeholder="Phone Number ..." class='form-control'>
                </div>
            </div>
            <div class="form-group">
                <label for="room" class="col-md-2 control-label">Room</label>
                <div class="col-md-4">
                    <input type="text" id='room' name='room' placeholder="Room ..." class='form-control'>
                </div>
            </div>
            <div class="form-actions nobg fluid">
                <div class="col-md-offset-2">
                    <button class="btn" id='btn-ok' name='ok' type='submit'>Tạo</button>
                </div>
            </div
        </form>
    </div>