<?php if (isset($message) && count($message)): ?>
    <div class="col-md-12 col-sm-12 col-xs-12 alert alert-danger">
        <ul>
            <?php foreach ($message as $key => $msg): ?>
                <li>
                    <span>
                        <?php echo $this->translate($key.'_error') ;?>
                    </span>
                    <ul>
                        <?php foreach ($msg as $mskey => $msgv): ?>
                            <li><?php echo $mskey . ': ' . $msgv; ?></li>
                        <?php endforeach; ?>
                    </ul>
                </li>
            <?php endforeach; ?>
        </ul>


    </div>
<?php endif; ?>
<?php
$form->setAttribute('action', $this->url('users', array('action' => 'save')));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
?>
<?php echo $this->form()->openTag($form); ?>
<!--<form class="form-horizontal" action="users" method="post" id="form-add">-->
<div class="form-group">
    <label for="username" class="col-md-2 control-label"><?php echo $this->translate('USERNAME_TITLE'); ?></label>
    <div class="col-md-10">
        <?php echo $this->formRow($form->get('username')); ?>
    </div>
</div>
<div class="form-group">
    <label for="fullname" class="col-md-2 control-label"><?php echo $this->translate('FULLNAME_TITLE'); ?></label>
    <div class="col-md-10">
        <?php echo $this->formRow($form->get('fullname')); ?>
    </div>
</div>
<div class="form-group">
    <label for="password" class="col-md-2 control-label"><?php echo $this->translate('PASSWORD_TITLE'); ?></label>
    <div class="col-md-10">
        <?php echo $this->formRow($form->get('password')); ?>
    </div>
</div>
<div class="form-group">
    <label for="re-password" class="col-md-2 control-label"><?php echo $this->translate('RETYPEPASSWORD_TITLE'); ?></label>
    <div class="col-md-10">
        <?php echo $this->formRow($form->get('retype')); ?>
    </div>
</div>
<div class="form-group">
    <label for="email" class="col-md-2 control-label"><?php echo $this->translate('EMAIL_TITLE'); ?></label>
    <div class="col-md-10">
        <?php echo $this->formRow($form->get('email')); ?>
    </div>
</div>
<div class="form-group">
    <label for="phonenumber" class="col-md-2 control-label"><?php echo $this->translate('PHONE_TITLE'); ?></label>
    <div class="col-md-10">
        <?php echo $this->formRow($form->get('phone')); ?>
    </div>
</div>
<div class="form-group">
    <label for="building" class="col-md-2 control-label"><?php echo $this->translate('BUILDING_TITLE'); ?></label>
    <div class="col-md-10">
        <?php echo $this->formRow($form->get('building')); ?>
    </div>
</div>
<div class="form-group">
    <label for="room" class="col-md-2 control-label"><?php echo $this->translate('ROOM_TITLE'); ?></label>
    <div class="col-md-10">
        <?php echo $this->formRow($form->get('room')); ?>
    </div>
</div>
<div class="form-group">
    <label for="room" class="col-md-2 control-label"><?php echo $this->translate('PACKET_TITLE'); ?></label>
    <div class="col-md-10">
        <?php echo $this->formRow($form->get('packet')); ?>
    </div>
</div>
<div class="form-actions nobg fluid">
    <div class="col-md-offset-2">
        <button class="btn btn-success" id='btn-ok' name='ok' type='submit'><?php echo $this->translate('SUBMIT_TITLE'); ?></button>
    </div>
</div>
<input type="hidden" name="id" value="<?php echo $data['id']?>">
<input type="hidden" name="created" value="<?php echo $data['created']?>">
<input type="hidden" name="created_by" value="<?php echo $data['created_by']?>">
<?php $this->form()->closeTag();?>
<script>
    $('#form-edit').submit(function(){
        k = 0;
        $('input').each(function(){
            if($(this).val()===''){
                $(this).css('border','1px solid red');
                k = 1;
            }            
        });
        if(k===1){
            alert('Please input all field required');
            return false;
        }
    })
</script>
