<div class="row">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-12 col-xs-12">
                <div class="pull-left">
                    <div class="input-group custom-search-form">
                        <input type="text" class="form-control" placeholder="Search...">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                </div>
                <div class="pull-right">
                    <?php echo $this->partial('partials/shared/menuaction.phtml', array('buttons' => $buttons)); ?>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="container-fluid">
        <?php if ($items): ?>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <td>
                            <input type="checkbox">
                        </td>
                        <td>
                            <?php echo $this->translate('TABLE_HEAD_ID'); ?>
                        </td> 
                        <td>
                            <?php echo $this->translate('TABLE_HEAD_USERNAME'); ?>
                        </td> 
                        <td>
                            <?php echo $this->translate('TABLE_HEAD_EMAIL'); ?>
                        </td> 
                        <td>
                            <?php echo $this->translate('TABLE_HEAD_STATUS'); ?>
                        </td>
                        <td>
                            <?php echo $this->translate('TABLE_HEAD_CREATED'); ?>
                        </td> 
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($items as $key => $value): ?>
                        <tr>
                            <td>
                                <input type="checkbox" name="">
                            </td>
                            <td>
                                <?php echo $value->getId(); ?>
                            </td> 
                            <td>
                                <?php echo $value->getUsername(); ?>
                            </td> 
                            <td>
                                <?php echo $value->getEmail(); ?>
                            </td> 
                            <td class="link">

                                <?php if ($value->getActivate()): ?>
                                    <a class="link linkActive" data-id="<?php echo $value->getId(); ?>"><span class="fa fa-anchor "></span></a>
                                <?php else: ?>
                                    <a class="linkDeactive" data-id="<?php echo $value->getId(); ?>"><span class="fa fa-download "></span></a>
                                    <?php endif; ?>

                            </td> 
                            <td>
                                <?php echo date($value->getCreated()); ?>
                            </td> 
                        </tr>
                    <?php endforeach; ?>
                </tbody>

            </table>
        <?php endif;
        ?>
    </div>
</div>
