<div class="row">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-12 col-xs-12">
                <div class="pull-left">
                    <div class="input-group custom-search-form">
                        <input type="text" class="form-control" placeholder="Search...">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                </div>
                <div class="pull-right">
                    <div class="pull-right">
                        <a class="btn btn-primary" href="/users/add">Thêm</a>
                        <a class="btn btn-primary edit-user">Sửa</a>
                        <a class="btn btn-primary del-user">Xóa</a>
                </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="clearfix" style="height: 30px"></div>
<div class="row">
    <div class="container-fluid">
        <?php if ($items): ?>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <td>
                            <input type="checkbox" class="check_all">
                        </td>
                        <td>
                            <?php echo $this->translate('TABLE_HEAD_ID'); ?>
                        </td> 
                        <td>
                            <?php echo $this->translate('TABLE_HEAD_USERNAME'); ?>
                        </td> 
                        <td>
                            <?php echo $this->translate('TABLE_HEAD_EMAIL'); ?>
                        </td> 
                        <td>
                            <?php echo $this->translate('TABLE_HEAD_STATUS'); ?>
                        </td>
                        <td>
                            <?php echo $this->translate('TABLE_HEAD_CREATED'); ?>
                        </td> 
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($items as $key => $value): ?>
                        <tr>
                            <td>
                                <input type="checkbox" name="check" class="check" value="<?php echo $value->getId();?>">
                            </td>
                            <td class="id">
                                <?php echo $value->getId(); ?>
                            </td> 
                            <td>
                                <?php echo $value->getUsername(); ?>
                            </td> 
                            <td>
                                <?php echo $value->getEmail(); ?>
                            </td> 
                            <td class="link">
                                 <?php echo $value->getActivate(); if($value->getActivate()==1) echo 'Actived'; else echo 'Non-active'; ?>
                            </td> 
                            <td>
                                <?php echo date($value->getCreated()); ?>
                            </td> 
                        </tr>
                    <?php endforeach; ?>
                </tbody>

            </table>
        <?php endif;
        ?>
    </div>
</div>
