<?php $buttons = $this->buttons;?>
<a class="btn btn-primary" href="<?php echo $this->url($buttons['add']['route'],array('action'=>$buttons['add']['action']));?>"><?php echo $this->translate('MENU_ADD_TITLE');?></a>
<a class="btn btn-primary" href="<?php echo $this->url($buttons['edit']['route'],array('action'=>$buttons['edit']['action']));?>"><?php echo $this->translate('MENU_EDIT_TITLE');?></a>
<a class="btn btn-primary" href="<?php echo $this->url($buttons['delete']['route'],array('action'=>$buttons['delete']['action']));?>"><?php echo $this->translate('MENU_DELETE_TITLE');?></a>
