
<form class="form-horizontal" action="editUser" method="post" id="form-edit">
        	<div class="form-group">
                <label for="username" class="col-md-2 control-label">Username</label>
                <div class="col-md-4">
                    <input type="text" value="<?php echo $user->getUsername(); ?>" id='username' name='username' placeholder="Username ..." class='form-control'>
                </div>
            </div>
            <div class="form-group">
                <label for="fullname" class="col-md-2 control-label">Fullname</label>
                <div class="col-md-4">
                    <input type="text" value="<?php echo $user->getFullname(); ?>" id='fullname' name='fullname' placeholder="Fullname ..." class='form-control'>
                </div>
            </div>
            <div class="form-group">
                <label for="password" class="col-md-2 control-label">Password</label>
                <div class="col-md-4">
                    <input type="password" id='password' name='password' placeholder="Password ..." class='form-control'>
                </div>
            </div>
            <div class="form-group">
                <label for="email" class="col-md-2 control-label">Email</label>
                <div class="col-md-4">
                    <input type="email" id='email' value="<?php echo $user->getEmail(); ?>" name='email' placeholder="Email ..." class='form-control'>
                </div>
            </div>
            <div class="form-group">
                <label for="phonenumber" class="col-md-2 control-label">Phone Number</label>
                <div class="col-md-4">
                    <input type="text" id='phonenumber' value="<?php echo $user->getPhone(); ?>" name='phone' placeholder="Phone Number ..." class='form-control'>
                </div>
            </div>
            <div class="form-group">
                <label for="room" class="col-md-2 control-label">Room</label>
                <div class="col-md-4">
                    <input type="text" id='room' value="<?php echo $user->getRoom(); ?>" name='room' placeholder="Room ..." class='form-control'>
                </div>
            </div>
            <div class="form-group">
                <label for="packet" class="col-sm-2 control-label">Packet</label>
                <div class="col-sm-4">
                    <select class="form-control" name="packet">
                       <?php foreach ($packet as $item): ?>
                        <option <?php if($user->getPacket()==$item->getId()) echo 'selected="selected"'; ?>  value="<?php echo $item->getId(); ?>"><?php echo $item->getName(); ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label for="room" class="col-md-2 control-label">Building</label>
                <div class="col-md-4">
                    <input type="text" id='room' value="<?php echo $user->getBuilding(); ?>" name='building' placeholder=" ..." class='form-control'>
                </div>
            </div>
            <div class="form-actions nobg fluid">
                <div class="col-md-offset-2">
                    <button class="btn" value="<?php echo $user->getID(); ?>" id='btn-ok' name='id' type='submit'>Save</button>
                </div>
            </div>
        </form>
<script>
    $('#form-edit').submit(function(){
        k = 0;
        $('input').each(function(){
            if($(this).val()===''){
                $(this).css('border','1px solid red');
                k = 1;
            }            
        });
        if(k===1){
            alert('Please input all field required');
            return false;
        }
    })
</script>
