<div class="row">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-12 col-xs-12">
                <div class="pull-left">
                    <div class="input-group custom-search-form">
                        <input type="text" class="form-control" placeholder="Search...">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                </div>
                <div class="pull-right">
                    <div class="pull-right">
                        <a class="btn btn-primary" href="/users/add">Thêm</a>
                        <a class="btn btn-primary edit-user">Sửa</a>
                        <a class="btn btn-primary del-user">Xóa</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="clearfix" style="height: 30px"></div>
<div class="row">
    <div class="container-fluid">
        <?php if ($items): ?>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <td>
                            <input type="checkbox" class="check_all">
                        </td>
                        <td>
                            <?php echo $this->translate('TABLE_HEAD_ID'); ?>
                        </td> 
                        <td>
                            <?php echo $this->translate('TABLE_HEAD_USERNAME'); ?>
                        </td> 
                        <td>
                            <?php echo $this->translate('TABLE_HEAD_EMAIL'); ?>
                        </td> 
                        <td>
                            <?php echo $this->translate('TABLE_HEAD_STATUS'); ?>
                        </td>
                        <td>
                            <?php echo $this->translate('TABLE_HEAD_CREATED'); ?>
                        </td> 
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($items as $key => $value): ?>
                        <tr>
                            <td>
                                <input type="checkbox" name="check" class="check" value="<?php echo $value['id']; ?>">
                            </td>
                            <td class="id">
                                <?php echo $value['id']; ?>
                            </td> 
                            <td>
                                <?php echo $value['username']; ?>
                            </td> 
                            <td>
                                <?php echo $value['email']; ?>
                            </td> 
                            <td class="link">
                                <?php
                                echo $value['activate'];
                                if ($value['activate'] == 1)
                                    echo 'Actived';
                                else
                                    echo 'Non-active';
                                ?>
                            </td> 
                            <td>
                                <?php echo date($value['created']); ?>
                            </td> 
                        </tr>
                    <?php endforeach; ?>
                </tbody>

            </table>
            <?php
            // add at the end of the file after the table
            echo $this->paginationControl(
                    // the paginator object
                    $this->paginator,
                    // the scrolling style
                    'sliding',
                    // the partial to use to render the control
                    'partials/shared/paging.phtml',
                    // the route to link to when a user clicks a control link
                    array(
                'route' => 'users',
                        'options' => array()
                    )
            );
            ?>
        <?php endif; ?>
    </div>
</div>
<script>
    $('.check').click(function () {
        if ($(this).prop('checked')) {
            current = $(this);
            $('.check').prop('checked', false);
            current.prop('checked', true);
            p = $(this).parent().parent().find('.id').html();
            if (!$('.checkall').prop('checked{')) {
                $(document).find('.del-user').attr('href', 'users/delete?id=' + p);
                $(document).find('.edit-user').attr('href', 'users/edit?id=' + p);
            }
        }
        else {
            $(document).find('.del-user').attr('href', '');
            $(document).find('.edit-user').attr('href', '');
        }
    });
    $('.check_all').click(function () {
        if ($(this).prop('checked')) {
            $('.check').prop('checked', true);
            $(document).find('.del-user').attr('href', 'users/deleteAll');
        }
        else {
            $('.check').prop('checked', false);
            $(document).find('.del-user').attr('href', '');
        }
    });
    $('.del-user').click(function () {
        k = 0;
        $('.check').each(function () {
            if ($(this).prop('checked')) {
                k = 1;
            }
        })
        if (k == 1)
            confirm('Do you want to delete this user');
    })
</script>

