<?php $form = $this->form;
    $form->prepare();
?>
<div class="row">
    <div class="col-sm-12 col-xs-12 col-md-12">
        <form class="form-horizontal" action="<?php $this->url('modules',array('action'=>'add'));?>" method="post">
            <div class="form-group">
                <label for="name" class="col-sm-2 control-label"><?php echo $this->translate('MUDOLE_NAME_TITLE'); ?></label>
                <div class="col-sm-10">
                    <?php echo $this->formRow($form->get('name'));?>
                </div>
            </div>
            <div class="form-group">
                <label for="attribute" class="col-sm-2 control-label"><?php echo $this->translate('MODULE_ATRRIBUTE'); ?></label>
                <div class="col-sm-10">
                    <?php echo $this->formRow($form->get('attribute'));?>

                </div>
            </div>
            <div class="form-group">
                
                <label for="" class="col-sm-2 control-label"><?php echo $this->translate('MODULE_STATUS'); ?></label>
                <div class="col-sm-10">
                    <div class="col-sm-6">
                        <label for="status_on" class="col-sm-2 control-label"><?php echo $this->translate('MODULE_STATUS_ON'); ?></label>
                        <div class="col-sm-10">
                            <?php echo $this->formRow($form->get('status'));?>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <label for="status_off" class="col-sm-2 control-label"><?php echo $this->translate('MODULE_STATUS_OFF'); ?></label>
                        <div class="col-sm-10">
                            <?php echo $this->formRow($form->get('status'));?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label for="" class="col-sm-2 control-label"><?php echo $this->translate('MODULE_DESCRIPTION_TITLE'); ?></label>
                <div class="col-sm-10">
                    <?php echo $this->formRow($form->get('description'));?>
                </div>
               
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default"></button>
                    <button type="cancel" class="btn btn-default">Sign in</button>
                </div>
            </div>
        </form>
    </div>
</div>