<?php
//$form = $this->form;
//$form->setAttribute('action', $this->url('modules', array('action' => 'addcategory')));
//$form->setAttribute('class', 'form-horizontal');
$form->prepare();
?>
<div class="row">
    <div class="col-sm-12 col-xs-12 col-md-12">

        <?php echo $this->form()->openTag($form); ?>

        <div class="form-group">
            <label for="name" class="col-sm-2 control-label">Category Name</label>
            <div class="col-sm-5">
                <?php echo $this->formRow($form->get('name')) ?>
<!--                    <input type="text" id='name' name='name' placeholder="Category name ..." class='form-control'>-->
            </div>
        </div>
        <div class="form-group">
            <label for="description" class="col-sm-2 control-label">Description</label>
            <div class="col-sm-5">
                <?php echo $this->formRow($form->get('description')) ?>
<!--                    <input type="text" id='description' name='description' placeholder="Description ..." class='form-control'>-->
            </div>
        </div>
        <div class="form-group">
            <label for="description" class="col-sm-2 control-label">Description</label>
            <div class="col-sm-5">
                <?php echo $this->formRow($form->get('value')) ?>
<!--                    <input type="text" id='description' name='description' placeholder="Description ..." class='form-control'>-->
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default"><?php echo $this->translate('MODULE_ADD_BUTTON_TITLE'); ?></button>
                <button type="reset" class="btn btn-default linkCancle"><?php echo $this->translate('MODULE_CANCLE_BUTTON_TITLE'); ?></button>
            </div>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>