<div class="row">
    <div class="col-sm-12 col-md-12 col-xs-12">
        <div class="pull-right">
            <?php echo $this->partial('partials/shared/menuaction.phtml', array('buttons' => $buttons)); ?>
        </div>
    </div>
</div>
<div class="clearfix" style="height: 20px"></div>
<div class="container-fluid text-center">
    <form id="adminForm" method="post" name="adminForm" action="">
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <td>
                        <input type="checkbox" class="check_all">
                    </td>
                    <td class="col-md-1 col-xs-12">
                        ID
                    </td>
                    <td class="col-md-6 col-xs-12">
                        Packet Name
                    </td>
                    <td class="col-md-5 col-xs-12">
                        Description
                    </td>
                </tr>
            </thead>
            <tbody>

                <?php if ($items): ?>
                    <?php foreach ($items as $item): ?>
                        <tr>
                            <td>
                                <input type="checkbox" class="checked" name="edit[<?php echo $item['id']; ?>]" value="<?php echo $item['id']; ?>">
                            </td>
                            <td class="col-md-1 col-xs-12 id">
                                <?php echo $item['id']; ?>
                            </td>
                            <td class="col-md-6 col-xs-12">
                                <?php echo $item['name']; ?>
                            </td>
                            <td class="col-md-5 col-xs-12">
                                <?php echo $item['description']; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>

                <?php else: ?>
                    <tr>
                        <td colspan="3" class="alert alert-danger">
                            <?php echo $this->translate("NO_RESULT"); ?>
                        </td>

                    </tr>

                <?php endif; ?>

            </tbody>
        </table>
    </form>
    <?php
    // add at the end of the file after the table
    echo $this->paginationControl(
            // the paginator object
            $this->paginator,
            // the scrolling style
            'sliding',
            // the partial to use to render the control
            'partials/shared/paging.phtml',
            // the route to link to when a user clicks a control link
            array(
        'route' => 'modules',
        'options' => array('action' => 'category')
    ));
    ?>
</div>
<script>
//    $('.check').click(function(){
//        if($(this).prop('checked')){
//            current = $(this);
//            $('.check').prop('checked',false);
//            current.prop('checked',true);
//            p = $(this).parent().parent().find('.id').html();
//            if(!$('.checkall').prop('checked{')){
//                $(document).find('.del-user').attr('href','deletecategory?id='+p);
//                $(document).find('.edit-user').attr('href','editcategory?id='+p);
//            }
//        }
//        else{
//            $(document).find('.del-user').attr('href','');
//            $(document).find('.edit-user').attr('href','');
//        }
//    });
//    $('.check_all').click(function(){
//        if($(this).prop('checked')){
//            $('.check').prop('checked',true);
//            $(document).find('.del-user').attr('href','deleteAllcategory');
//        }
//        else{
//            $('.check').prop('checked',false);
//            $(document).find('.del-user').attr('href','');
//        }
//    });
//    $('.del-user').click(function(){
//        k = 0;
//        $('.check').each(function(){
//            if($(this).prop('checked')){
//                k = 1;
//            }
//        })
//        if(k==1)
//            confirm('Do you want to delete this Category');
//    })
</script>