
<div class="row">
    <div class="col-sm-12 col-xs-12 col-md-12">
        <form class="form-horizontal" action="editct" method="post"v id="form-edit">
            <div class="form-group">
                <label for="name" class="col-sm-2 control-label">Category Name</label>
                <div class="col-sm-5">
                    <input type="text" value="<?php echo $category->getName(); ?>" id='name' name='name' placeholder="Category name ..." class='form-control'>
                </div>
            </div>
            <div class="form-group">
                <label for="description" class="col-sm-2 control-label">Description</label>
                <div class="col-sm-5">
                        <input type="text" value="<?php echo $category->getDescription(); ?>" id='description' name='description' placeholder="Description ..." class='form-control'>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" value="<?php echo $category->getID(); ?>" name="id" class="btn btn-default">Save</button>
                    <button type="reset" class="btn btn-default linkCancle"><?php echo $this->translate('MODULE_CANCLE_BUTTON_TITLE'); ?></button>
                </div>
            </div>
        </form>
    </div>
</div>
<script>
    $('#form-edit').submit(function(){
        k = 0;
        $('input').each(function(){
            if($(this).val()===''){
                $(this).css('border','1px solid red');
                k = 1;
            }            
        });
        if(k===1){
            alert('Please input all field required');
            return false;
        }
    })
</script>