<?php if (isset($message) && count($message)): ?>
    <div class="col-md-12 col-sm-12 col-xs-12 alert alert-danger">
        <ul>
            <?php foreach ($message as $key => $msg): ?>
                <li>
                    <span>
                        <?php echo $this->translate($key . '_error'); ?>
                    </span>
                    <ul>
                        <?php foreach ($msg as $mskey => $msgv): ?>
                            <li><?php echo $mskey . ': ' . $msgv; ?></li>
                        <?php endforeach; ?>
                    </ul>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
<?php
$form->setAttribute('action', $this->url('modules', array('action' => 'savepacket')));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
?>
<?php echo $this->form()->openTag($form); ?>
<div class="row">
    <div class="col-sm-12 col-xs-12 col-md-12">
        <?php echo $this->form()->openTag($form); ?>
        <div class="form-group">
            <label for="name" class="col-sm-2 control-label"><?php echo $this->translate('PACKET_NAME_TITLE'); ?></label>
            <div class="col-sm-10">
                <?php echo $this->formRow($form->get('name')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="category" class="col-sm-2 control-label"><?php echo $this->translate('FORM_SELECT_CATEGORY'); ?></label>
            <div class="col-sm-10">
                <?php echo $this->formRow($form->get('category')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="price" class="col-sm-2 control-label"><?php echo $this->translate('PACKET_PRICE_TITLE'); ?></label>
            <div class="col-sm-10">
                <?php echo $this->formRow($form->get('price')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="unit" class="col-sm-2 control-label"><?php echo $this->translate('PACKET_UNIT_TITLE'); ?></label>
            <div class="col-sm-10">
                <?php echo $this->formRow($form->get('unit')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="value" class="col-sm-2 control-label"><?php echo $this->translate('PACKET_VALUE_TITLE'); ?></label>
            <div class="col-sm-10">
                <?php echo $this->formRow($form->get('value')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="description" class="col-sm-2 control-label"><?php echo $this->translate('PACKET_DESC_TITLE'); ?></label>
            <div class="col-sm-10">
                <?php echo $this->formRow($form->get('description')); ?>
            </div>
        </div>
        <input name="id" value="<?php echo $item->getId()?>" hidden="">
        <input name="created" value="<?php echo $item->getCreated()?>" hidden="">
        <input name="created_by" value="<?php echo $item->getCreatedBy()?>" hidden="">
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default"><?php echo $this->translate('MODULE_ADD_BUTTON_TITLE'); ?></button>
                <button type="reset" class="btn btn-default linkCancel" data-href="/modules/packet"><?php echo $this->translate('MODULE_CANCLE_BUTTON_TITLE'); ?></button>
            </div>
        </div>
        </form>
    </div>
</div>