<div class="row">
    <div class="col-sm-12 col-md-12 col-xs-12">
        <div class="pull-right">
            <?php echo $this->partial('partials/shared/menuaction.phtml', array('buttons' => $buttons)); ?>
        </div>
    </div>
</div>
<div class="clearfix" style="height: 20px"></div>
<div class="container-fluid text-center">
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <td>
                    <?php echo $this->translate('SELECT_EDIT'); ?>
                </td>
                <td class="col-md-1 col-xs-12">
                    <?php echo $this->translate('ID'); ?>
                </td>
                <td class="col-md-6 col-xs-12">
                    <?php echo $this->translate('MUDOLE_NAME_TITLE'); ?>
                </td>
                <td class="col-md-5 col-xs-12">
                    <?php echo $this->translate('MODULE_ACTION_TITLE'); ?>
                </td>
            </tr>
        </thead>
        <tbody>
        <form id="adminForm" method="post" name="adminForm" action="">
            <?php if ($items): ?>

                <?php foreach ($items as $item): ?>
                    <tr>
                        <td>
                            <input type="checkbox" class="checked" name="edit[<?php echo $item->getId(); ?>]" value="<?php echo $item->getId(); ?>">
                        </td>
                        <td class="col-md-1 col-xs-12">
                            <?php echo $item->getId(); ?>
                        </td>
                        <td class="col-md-6 col-xs-12">
                            <?php echo $item->getName(); ?>
                        </td>
                        <td class="col-md-5 col-xs-12">
                            <form method="post" style="display: inline" action="modules/listnguoidung"><button type="submit" name="module_attribute" value="<?php echo $item->getAttribute(); ?>" class="btn btn-info btn-xs " style="border-radius: 0px; border:none; padding: 5px">List Người Dùng</button></a></form>
                            <button style="border-radius: 0px; border:none; padding:5px" type="button" id="add" class="add btn btn-danger btn-xs" data-toggle="modal" data-target="#myModal<?php echo $item->getId(); ?>">Thêm User</button>
                            <div class="clearfix"></div>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="3" class="alert alert-danger">
                        <?php echo $this->translate("NO_RESULT"); ?>
                    </td>

                </tr>

            <?php endif; ?>
        </form>
        </tbody>
    </table>
</div>
<?php foreach ($items as $item): ?>
<div class="modal fade" id="myModal<?php echo $item->getId(); ?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Thêm Người Dùng</h4>
            </div>
            <form class="form-horizontal" action="modules/adduser" method="post">
            <div class="modal-body">
                    <div class="form-group">
                        <label for="packet" class="col-sm-2 control-label">Username</label>
                        <div class="col-sm-10">
                            <select class="form-control" name="user_id">
                               <?php foreach ($user as $i): ?>
                                <option value="<?php echo $i->getId(); ?>"><?php echo $i->getUsername(); ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
            </div>
            <div class="modal-footer">
                <input type="hidden" value="<?php echo $item->getAttribute(); ?>" name="module_attribute" />
                <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
                <button type="submit" class="btn btn-primary">Thêm</button>
            </div>
            </form>
        </div>
    </div>
</div>
<?php endforeach; ?>
