<div class="row">
    <div class="col-sm-12 col-md-12 col-xs-12">
        <div class="pull-right">
            <?php echo $this->partial('partials/shared/menuaction.phtml', array('buttons' => $buttons)); ?>
        </div>
    </div>
</div>
<div class="container-fluid text-center">
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <td class="col-md-1 col-xs-12">
                    <?php echo $this->translate('ID'); ?>
                </td>
                <td class="col-md-6 col-xs-12">
                    <?php echo $this->translate('MUDOLE_NAME_TITLE'); ?>
                </td>
                <td class="col-md-5 col-xs-12">
                    <?php echo $this->translate('MODULE_ACTION_TITLE'); ?>
                </td>
            </tr>
        </thead>
        <tbody>
            <?php if ($items): ?>
                <?php foreach ($items as $item): ?>
                    <tr>
                        <td class="col-md-1 col-xs-12">
                            <?php echo $item->getId(); ?>
                        </td>
                        <td class="col-md-6 col-xs-12">
                            <?php echo $item->getName(); ?>
                        </td>
                        <td class="col-md-5 col-xs-12">
                            <a href="listnguoidung.html"><button type="button" class="btn btn-info btn-xs ">List Người Dùng</button></a>
                            <button type="button" id="add" class="btn btn-danger btn-xs" data-toggle="modal" data-target="#myModal">Thêm User</button>
                            <div class="clearfix"></div>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="3" class="alert alert-danger">
                        <?php echo $this->translate("NO_RESULT"); ?>
                    </td>

                </tr>

            <?php endif; ?>
        </tbody>
    </table>
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Thêm Người Dùng</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                    <div class="form-group">
                        <label for="username" class="col-md-2 control-label">Username</label>
                        <div class="col-md-8">
                            <input type="text" id='username' name='username' placeholder="Username ..." class='form-control'>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="email" class="col-md-2 control-label">Email</label>
                        <div class="col-md-8">
                            <input type="email" id='email' name='email' placeholder="Email ..." class='form-control'>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
                <button type="button" class="btn btn-primary">Thêm</button>
            </div>
        </div>
    </div>