<div class="row">
    <div class="col-sm-12 col-md-12 col-xs-12">
        <div class="pull-right">
            <?php echo $this->partial('partials/shared/menuaction.phtml', array('buttons' => $buttons)); ?>
        </div>
    </div>
</div>
<div class="clearfix" style="height: 20px"></div>
<div class="container-fluid text-center">
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <td>
                    <input type="checkbox" class="check_all">
                </td>
                <td class="col-md-1 col-xs-12">
                    ID
                </td>
                <td class="col-md-4 col-xs-12">
                    Packet Name
                </td>
                <td class="col-md-4 col-xs-12">
                    Category
                </td>
                <td class="col-md-2 col-xs-12">
                    Price
                </td>
                <td class="col-md-1 col-xs-12">
                    Unit
                </td>

            </tr>
        </thead>
        <tbody>
        <form id="adminForm" method="post" name="adminForm" action="">
            <?php if ($items): ?>
                <?php foreach ($items as $item): ?>
                    <tr>
                        <td>
                            <input type="checkbox" class="checked" name="edit[<?php echo $item['id']; ?>]" value="<?php echo $item['id']; ?>">
                        </td>
                        <td class="col-md-1 col-xs-12 id">
                            <?php echo $item['id']; ?>
                        </td>
                        <td class="col-md-4 col-xs-12">
                            <?php echo $item['name']; ?>
                        </td>
                        <td class="col-md-4 col-xs-12">
                            <?php echo $item['category_name'] ?>
                        </td>
                        <td class="col-md-2 col-xs-12">
                            <?php echo $item['price']; ?>
                        </td>
                        <td class="col-md-1 col-xs-12">
                            <?php echo $item['unit']; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </form>
            <tr>
                <td colspan="7">
                    <?php
                    // add at the end of the file after the table
                    echo $this->paginationControl(
                            // the paginator object
                            $this->paginator,
                            // the scrolling style
                            'sliding',
                            // the partial to use to render the control
                            'partials/shared/paging.phtml',
                            // the route to link to when a user clicks a control link
                            array(
                        'route' => 'modules',
                        'options' => array('action' => 'packet')
                    ));
                    ?>
                </td>
            </tr>
<?php else: ?>
            <tr>
                <td colspan="3" class="alert alert-danger">
    <?php echo $this->translate("NO_RESULT"); ?>
                </td>

            </tr>

<?php endif; ?>
        </tbody>
    </table>

</div>
<script>

</script>