<div class="row">
    <div class="col-sm-12 col-md-12 col-xs-12">
        <div class="pull-right">
            <a class="btn btn-primary" href="addpacket">Thêm</a>
            <a class="btn btn-primary edit-user">Sửa</a>
            <a class="btn btn-primary del-user">Xóa</a>
        </div>
    </div>
</div>
<div class="clearfix" style="height: 20px"></div>
<div class="container-fluid text-center">
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <td>
                    <input type="checkbox" class="check_all">
                </td>
                <td class="col-md-1 col-xs-12">
                    ID
                </td>
                <td class="col-md-4 col-xs-12">
                    Packet Name
                </td>
                <td class="col-md-4 col-xs-12">
                    Category
                </td>
                <td class="col-md-2 col-xs-12">
                    Price
                </td>
                <td class="col-md-1 col-xs-12">
                    Unit
                </td>
                
            </tr>
        </thead>
        <tbody>
            <?php if ($items): ?>
                <?php foreach ($items as $item): ?>
                    <tr>
                        <td>
                            <input type="checkbox" name="check" class="check">
                        </td>
                        <td class="col-md-1 col-xs-12 id">
                            <?php echo $item->getId(); ?>
                        </td>
                        <td class="col-md-4 col-xs-12">
                            <?php echo $item->getName(); ?>
                        </td>
                        <td class="col-md-4 col-xs-12">
                            <?php $c = $category->findByID($item->getCategory()); echo $c->getName(); ?>
                        </td>
                        <td class="col-md-2 col-xs-12">
                            <?php echo $item->getPrice(); ?>
                        </td>
                        <td class="col-md-1 col-xs-12">
                            <?php echo $item->getUnit(); ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="3" class="alert alert-danger">
                        <?php echo $this->translate("NO_RESULT"); ?>
                    </td>

                </tr>

            <?php endif; ?>
        </tbody>
    </table>
</div>
<script>
    $('.check').click(function(){
        if($(this).prop('checked')){
            current = $(this);
            $('.check').prop('checked',false);
            current.prop('checked',true);
            p = $(this).parent().parent().find('.id').html();
            if(!$('.checkall').prop('checked{')){
                $(document).find('.del-user').attr('href','deletepacket?id='+p);
                $(document).find('.edit-user').attr('href','editpacket?id='+p);
            }
        }
        else{
            $(document).find('.del-user').attr('href','');
            $(document).find('.edit-user').attr('href','');
        }
    });
    $('.check_all').click(function(){
        if($(this).prop('checked')){
            $('.check').prop('checked',true);
            $(document).find('.del-user').attr('href','deleteAllpacket');
        }
        else{
            $('.check').prop('checked',false);
            $(document).find('.del-user').attr('href','');
        }
    });
    $('.del-user').click(function(){
        k = 0;
        $('.check').each(function(){
            if($(this).prop('checked')){
                k = 1;
            }
        })
        if(k==1)
            confirm('Do you want to delete this Packet');
    })
</script>