<?php
if(isset($message)):
    echo $message;
endif;
$form->setAttribute('action', $this->url('login', array('action' => 'index','urlLogin' => $urlLogin)));
$form->prepare();
?>
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title alert alert-success" style="text-align: center; color: #202020; text-transform: uppercase; font-size: 20px"><?php echo $this->translate('_WELLCOME');?></h3>
                    <p style="text-align: center; font-size: 16px; margin-top: 10px"><?php echo $this->translate('MESSAGE_WELLCOME');?></p>
                </div>
                <div class="panel-body">
                    <?php echo $this->form()->openTag($form);?>
                        <fieldset>
                            <div class="form-group">
                                <?php echo $this->formRow($form->get('username')) ?>
                                
                            </div>
                            <div class="form-group">
                                <?php echo $this->formRow($form->get('password')) ?>
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input name="remember" type="checkbox" value="Remember Me">Remember Me
                                </label>
                            </div>
                            <!-- Change this to a button or input when using this as a form -->
                            <?php echo $this->formSubmit($form->get('submit')) ?>
                            
                        </fieldset>
                    <?php echo $this->form()->closeTag(); ?>
                </div>
            </div>
        </div>
    </div>
</div>

